export const scifyDevices = [
    "Flux Capacitor",
    "Hoverboard",
    "Neuralizer",
    "Lightsaber",
    "Electronic Thumb",
    "Mr. Fusion",
    "TARDIS",
    "Transporter",
    "Replicator",
    "Sonic Screwdriver",
    "KITT",
    "R2-D2",
    "Matter Compiler",
    "Tricorder",
    "Antigravity Battle Room",
    "Speeder Bike",
    "Heat-Ray",
    "Robot Maid",
    "Robot Vacuum",
    "Power Laces",
    "X-Wing",
    "Gadget Copter",
    "Liquid Breathing Apparatus",
    "Jetpack",
    "TV Glasses",
    "Scramble Suit",
    "Teleporter",
    "Point-of-view gun",
    "Battle Mech",
    "Flubber",
    "Electromagnetic Shrinking Machine",
    "Time Machine",
    "Flying Cab",
    "Esper Photo Analyser",
    "Lightcycle",
    "Dejarik",
    "Wall-E",
    "Memory Implanter",
    "Universal Remote",
    "Proton Packs",
    "T-800",
    "Translation Collar",
    "Massive Robot Spider",
    "P.K.E. Meter",
    "Ecto Goggles",
    "Holodeck",
    "Tractor Beam",
    "Warp Drive",
    "Carbonite Freezer",
    "Pip boy",
];
